plugins:
  - import
  - jest

env:
  jest: true
  browser: true

parserOptions:
  ecmaVersion: 2020

extends:
  - 'airbnb-base'
  - "plugin:jest/recommended"
  - 'prettier'

rules:
  import/extensions: 0